### ISSUE TITLE
Evaluation script / method

### ISSUE THREAD

**Issue by RubensCodeHub** [Chopper-233/Anomaly-ShapeNet#5]
Hello,

I really like your Dataset and use it for my own studies.
Of course I understand that you don't want to publish your code, before your paper has been accepted.

I would like to ask you to upload or reference the code you used for your evaluation. 
As of of yet I haven't found an adaption of the PRO/AUPRO metric to the 3d case (RealAD 3D uses 2d gt masks I believe).

If you could upload / explain how you calculated the AUPRO metric for the 3d case I would be extremely grateful :)

Thanks and best regards

**Comment by Chopper-233** [comment]
I'm glad you follow my work. My original code is too confusing and involves some other work, so I have no plans to upload it at the moment. If you need the code for anomaly map or other problem, you can give me an email address and I will send you the code.

**Comment by heidapao2b** [comment]
您能把您的代码发送到邮箱1744767845@qq.com吗，如果可以万分感谢您

**Comment by Chopper-233** [comment]
> 您能把您的代码发送到邮箱[1744767845@qq.com](mailto:1744767845@qq.com)吗，如果可以万分感谢您

Test code have been seet to you emailbox, Please check for it

**Comment by heidapao2b** [comment]
感谢

**Comment by zhouzheyuan** [comment]
Hi, thanks for your great work!

I am also very interested in the AURPO metric. Please send me (zheyuanzhou@zju.edu.cn) a copy of your test code as well, as it would be very helpful to me. Thanks!

**Comment by shyern** [comment]
Hi, thanks for your great work!

I am very interested in your work. Please send me (shyern3@163.com) a copy of your test code, as it would be very helpful to me. Many thanks!

**Comment by Chopper-233** [comment]
> Hi, thanks for your great work!
> 
> I am also very interested in the AUPRO metric. Please send me ([zheyuanzhou@zju.edu.cn](mailto:zheyuanzhou@zju.edu.cn)) a copy of your test code, as it would be very helpful to me. Many thanks!

check in the mailbox

**Comment by Chopper-233** [comment]
> Hi, thanks for your great work!
> 
> I am very interested in your work. Please send me ([shyern3@163.com](mailto:shyern3@163.com)) a copy of your test code, as it would be very helpful to me. Many thanks!

check in the mailbox
