### ISSUE TITLE
Should the reconstructed point cloud calculate the loss with the point cloud that has not been masked?

### ISSUE THREAD

**Issue by zhiqing0205** [Chopper-233/Anomaly-ShapeNet#7]
![image](https://img.ziuch.top/i/2024/04/29/119kssw-1709194236434.webp)

**Comment by Chopper-233** [comment]
only the masked group should be calculated loss,which forms to the setting for point-mae(https://github.com/Pang-Yatian/Point-MAE)

**Comment by zhiqing0205** [comment]
Thanks
