### ISSUE TITLE
About the point patch comparision

### ISSUE THREAD

**Issue by MAOXIXI-LV** [Chopper-233/Anomaly-ShapeNet#8]
Hello, 
Thanks for your outstanding work!
I have some questions. Regarding the point patch comparision mentioned in your paper, how is the correspondence between Pi and Po found after obtaining them using KNN? What is the approximate computational time for this part?  I would greatly appreciate it if you could provide the corresponding code.

**Comment by Chopper-233** [comment]
https://github.com/Chopper-233/Anomaly-ShapeNet/issues/5

**Comment by MAOXIXI-LV** [comment]
> #5

My email address is 13552734673@163.com.  Thanks.

**Comment by Chopper-233** [comment]
> > #5
> 
> My email address is [13552734673@163.com](mailto:13552734673@163.com). Thanks.

Test code have been seet to you emailbox, Please check for i

**Comment by Chopper-233** [comment]
> > #5
> 
> My email address is [13552734673@163.com](mailto:13552734673@163.com). Thanks.

code have been seet to you emailbox, Please check for it

**Comment by shyern** [comment]
My email address is shyern3@163.com. Thanks.

**Comment by shyern** [comment]
> #5

My email address is shyern3@163.com. Thanks.
